language: node_js
node_js:
  - "14"

cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

script:
  - pnpm test

after_script:
  - bash <(curl -s https://codecov.io/bash)

branchs:
  only:
    master
